version: "3"

services:
  frontend:
    image: aditi62/myfirstcicd:latest
    ports:
      - "4000:3000"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    image: myfirst-ci-cd-app_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"