version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    image: aditi62/myfirstcicd:latest
    ports:
      - "4000:3000"
    depends_on:
      - backend
