version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    image: aditi62/myfirstcicd:latest
    container_name: frontend
    ports:
      - "4000:3000"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
<<<<<<< HEAD
=======

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/testdb
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
>>>>>>> b064302 (fix backend hostname)
